---
title: "Quarto Test Tutorial 2"
format: html
---


# Tutorial 2
Date: 31-08/2026 2:112
Created for testing

```{r}
library(tidyverse)
library(ggplot2)
```

```{r}
getwd()
list.files()
```


```{r}
library(dplyr)
library(here)
data_path <- here("Tutorial 2", "video_view.csv")
if (!file.exists(data_path)) {
  data_url <- "https://raw.githubusercontent.com/hannesdatta/course-dprep/refs/heads/main/material/tutorials/r-bootcamp-rev/video_view.csv"
  download.file(data_url, data_path)
}
videos <- read_csv(data_path)

```

# Example 2

```{r}
watch_share <- videos %>%
    mutate(watch_share = watched_n / impressions_n) %>% 
    rename(impressions = impressions_n, watch_count = watched_n) %>% 
    arrange(desc(watch_share))
```

# Exercise 2

```{r}
creator_summary <- videos %>% 
    group_by(creator_id) %>% 
    summarise(videos_n = n(), impressions_total = sum(impressions_n), watch_rate_avg = mean(watch_rate)) %>% 
    arrange(desc(impressions_total))

creator_summary
```

# Exercise 3

```{r}
top_watch <- videos %>% 
    filter(impressions_n >= 50) %>% 
    select(video_id, creator_id, watch_rate) %>% 
    arrange(desc(watch_rate))

top_watch
```

# Exercise 4

```{r}
Engagement <- videos %>% 
    mutate(engagement = watched_n / impressions_n) %>% 
    group_by(creator_id) %>% 
    summarize(mean_engagement = mean(engagement)) %>% 
    arrange(desc(mean_engagement))

Engagement
```


```{r}
scatterplot <- ggplot(data = videos, aes(x = impressions_n, y = watch_rate, color = video_length_sec)) +
  geom_point(na.rm = FALSE, alpha = 0.6, size = 2.5) +
  labs(
    title = "Watch Rate vs. Impressions",
    subtitle = "Performance metrics by video length",
    x = "Impressions",
    y = "Watch Rate (%)",
    color = "Length of Video (Seconds)"
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(size = 14, face = "bold", hjust = 0.5),
    plot.subtitle = element_text(size = 11, color = "gray40"),
    axis.title = element_text(size = 11, face = "bold"),
    legend.position = "right"
  )

scatterplot
```